AWSTemplateFormatVersion: 2010-09-09
Description: "This CloudFormation template creates the IAM roles necessary for Amazon AppStream 2.0 to function correctly."
Resources:
  AmazonAppStreamServiceAccessRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: "AmazonAppStreamServiceAccess"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "appstream.amazonaws.com"
            Action:
              - 'sts:AssumeRole'
      Path: /service-role/
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonAppStreamServiceAccess"
  ApplicationAutoScalingForAmazonAppStreamAccessRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: "ApplicationAutoScalingForAmazonAppStreamAccess"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "application-autoscaling.amazonaws.com"
            Action:
              - 'sts:AssumeRole'
      Path: /service-role/
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/ApplicationAutoScalingForAmazonAppStreamAccess"
  AWSServiceRoleForApplicationAutoScalingAppStreamFleetRole:
    Type: 'AWS::IAM::ServiceLinkedRole'
    Properties:
      AWSServiceName: "appstream.application-autoscaling.amazonaws.com"
